translate_dict = {
   
    "en_US": {"On","Off","On",:"Off",
              "Delete Now","Safe Mode","Website",
              "Virus ","Malware ","Ransom ",
              "Script ","Behavior ",:"Suspicious ",
              "License Terms","Malicious","Suspicious",
              "Enable ","Disable ","Initializing ",
              "Scanning ","Deleting ","Minimize To ",
              "Sure Want To ","Sensitivity ","Update ",
              "White","Yellow","Red","Language ",
              "Blue","Green","Custom","Latest ",
              "Testers","Information","Communication ",
              "Registry ","Quit ","File ","Currently ",
              "State ","Scan ","Tools ","Protect ",
              "Failed ","Please ","Path ",:"Method ",
              "Need ","Virus ","Select ","Back",
              "Been ",""Error","Complete ","Engine ",
              "Tray ","Icon ","Unsafe","Enhanced ",
              "System ","Cloud ","Reboot ","Repair ",
              "Device ","Found ","成功":"Success ","Cleanup ",
              "OK","Execute ","Warning ","Use ",
              "Network ","Change ","Total","End ",
              "Options ","Monitor ","Connect ",:"To ",
              "Process ","Block ","Boot ","Delete ",
              "Partition ","Settings","About","Mode ",
              "Improve ","Security ","Color ","Themes ",
              "Risk ","GUI ","Core ","Services ",
              "Manage","All ","You ","Cancel ","Not ",
              "Junk ","byte ","Computer ","Stop ",
              "Add File To ","White List ","Software ",
              "Add","Delete","Items ","Create ",
              "Copy ","Open ","This ","And ","Full ",
              "Already ","Database ","False Positive ",
              "High ","New ","And ","Possible ","Can ",
              "Log","Has ","To ","Drive",
              "Key ","Detect ","Make","  ":" "}}
